services:
  horizon-db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - horizon-net
    environment:
      MYSQL_DATABASE: horizon
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  horizon-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7024:7024
    networks:
      - horizon-net
    environment:
      - spring.datasource.url=jdbc:mysql://horizon-db:3306/horizon
    depends_on:
      - horizon-db
    restart: always


networks:
  horizon-net: